For maths operations

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
a=np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(a)
print(type(a))

print(a.shape)

[[1 2 3 4 5]
 [5 4 3 2 1]]
<class 'numpy.ndarray'>
(2, 5)


In [8]:
# code for zero,one and constant array
zero_array = np.zeros((2,3))
print("Zero Array:")
print(zero_array)

one_array = np.ones((3,2))
print("\nOne Array:")
print(one_array)

constant_array = np.full((2,2), 7)
print("\nConstant Array:")
print(constant_array)

identity_matric = np.eye(4)
print("\nidentity_matric")
print(identity_matric)


random_matric = np.random.random((2,3))
print("\nrandom_matric")
print(random_matric)

Zero Array:
[[0. 0. 0.]
 [0. 0. 0.]]

One Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Constant Array:
[[7 7]
 [7 7]]

identity_matric
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

random_matric
[[0.86519642 0.36256479 0.87304271]
 [0.36210654 0.05140412 0.84450254]]


In [10]:
print(random_matric[:,1])
print(random_matric[1,:])

[0.36256479 0.05140412]
[0.36210654 0.05140412 0.84450254]


In [11]:
# code for array slicing
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Original array:")
print(a)

# Slice the array to get the first two rows and columns 1 to 3 (inclusive of 1, exclusive of 3)
sliced_array = a[:2, 1:3]
print("\nSliced array (first two rows, columns 1-2):")
print(sliced_array)

# Slice the array to get all rows and the last column
last_column = a[:, -1]
print("\nLast column of the array:")
print(last_column)

# Slice the array to get the last row and all columns
last_row = a[-1, :]
print("\nLast row of the array:")
print(last_row)

Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Sliced array (first two rows, columns 1-2):
[[2 3]
 [7 8]]

Last column of the array:
[ 5 10 15]

Last row of the array:
[11 12 13 14 15]


In [12]:
# maths operations using arrays in numpy

# Create two sample arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Addition
addition_result = array1 + array2
print("\nAddition:")
print(addition_result)

# Subtraction
subtraction_result = array1 - array2
print("\nSubtraction:")
print(subtraction_result)

# Multiplication (element-wise)
multiplication_result = array1 * array2
print("\nElement-wise Multiplication:")
print(multiplication_result)

# Division (element-wise)
division_result = array1 / array2
print("\nElement-wise Division:")
print(division_result)

# Dot product (matrix multiplication)
dot_product_result = np.dot(array1, array2)
print("\nDot Product (Matrix Multiplication):")
print(dot_product_result)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Element-wise Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Dot Product (Matrix Multiplication):
[[19 22]
 [43 50]]


In [13]:
# Stacking of 2 arrays in numpy

# Create two sample arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Vertical stacking
vertical_stack = np.vstack((array1, array2))
print("\nVertical Stack:")
print(vertical_stack)

# Horizontal stacking
horizontal_stack = np.hstack((array1, array2))
print("\nHorizontal Stack:")
print(horizontal_stack)

Array 1:
[1 2 3]

Array 2:
[4 5 6]

Vertical Stack:
[[1 2 3]
 [4 5 6]]

Horizontal Stack:
[1 2 3 4 5 6]


In [14]:
# Reshape function in numpy

# Create a sample array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original array:")
print(array)
print("Original shape:", array.shape)

# Reshape the array into a 3x4 matrix
reshaped_array = array.reshape((3, 4))
print("\nReshaped array (3x4):")
print(reshaped_array)
print("Reshaped shape:", reshaped_array.shape)

# Using -1 in reshape to automatically determine one dimension
reshaped_array_4 = array.reshape((3, -1))
print("\nReshaped array (3x?):")
print(reshaped_array_4)
print("Reshaped shape:", reshaped_array_4.shape)

reshaped_array_5 = array.reshape((-1, 4))
print("\nReshaped array (?x4):")
print(reshaped_array_5)
print("Reshaped shape:", reshaped_array_5.shape)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original shape: (12,)

Reshaped array (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped shape: (3, 4)

Reshaped array (3x?):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped shape: (3, 4)

Reshaped array (?x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped shape: (3, 4)


Numpy Random module

In [15]:
# Numpy important funcitons of random module

# Generate a 2x3 array of random numbers from a uniform distribution between 0 and 1
random_uniform = np.random.rand(2, 3)
print("Random array from uniform distribution (rand):")
print(random_uniform)

# Generate a 2x3 array of random numbers from a standard normal distribution (mean 0, variance 1)
random_normal = np.random.randn(2, 3)
print("\nRandom array from standard normal distribution (randn):")
print(random_normal)

# Generate a 2x3 array of random integers between 0 (inclusive) and 10 (exclusive)
random_integers = np.random.randint(0, 10, size=(2, 3))
print("\nRandom array of integers (randint):")
print(random_integers)

# Randomly choose an element from an array
choices = np.array([10, 20, 30, 40, 50])
random_choice = np.random.choice(choices)
print("\nRandom choice from an array (choice):")
print(random_choice)

# Randomly choose multiple elements from an array with replacement
random_choices_with_replacement = np.random.choice(choices, size=3, replace=True)
print("\nRandom choices with replacement (choice, replace=True):")
print(random_choices_with_replacement)

# Randomly choose multiple elements from an array without replacement
# Note: size must be less than or equal to the size of the array when replace=False
if len(choices) >= 3:
    random_choices_without_replacement = np.random.choice(choices, size=3, replace=False)
    print("\nRandom choices without replacement (choice, replace=False):")
    print(random_choices_without_replacement)
else:
    print("\nCannot perform random choices without replacement: size is larger than the array.")

# Shuffle an array in place
array_to_shuffle = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array_to_shuffle)
print("\nShuffled array (shuffle):")
print(array_to_shuffle)

Random array from uniform distribution (rand):
[[0.23815283 0.44136754 0.95359124]
 [0.0177984  0.86860158 0.55904801]]

Random array from standard normal distribution (randn):
[[-0.42850234 -1.03520876 -0.08708199]
 [-0.32060292  0.58279033 -0.64152665]]

Random array of integers (randint):
[[6 7 3]
 [0 6 2]]

Random choice from an array (choice):
40

Random choices with replacement (choice, replace=True):
[20 20 30]

Random choices without replacement (choice, replace=False):
[50 40 30]

Shuffled array (shuffle):
[3 2 4 1 5]


In [16]:
# simple random using seed

# Set the seed for reproducibility
np.random.seed(42)

# Generate random numbers after setting the seed
random_numbers_1 = np.random.rand(5)
print("Random numbers after setting seed 42 (first call):")
print(random_numbers_1)

# Generate more random numbers (will be different from the first set)
random_numbers_2 = np.random.rand(5)
print("\nRandom numbers after setting seed 42 (second call):")
print(random_numbers_2)

# Set the seed again to get the same sequence of random numbers as the first call
np.random.seed(42)

# Generate random numbers again (will be the same as random_numbers_1)
random_numbers_3 = np.random.rand(5)
print("\nRandom numbers after setting seed 42 again:")
print(random_numbers_3)

Random numbers after setting seed 42 (first call):
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Random numbers after setting seed 42 (second call):
[0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]

Random numbers after setting seed 42 again:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


Numpy Statistics functions

In [18]:
# Numpy Statistics functions

# Create a sample array
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original array:")
print(array)

#weighted average
weights = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])
weighted_average = np.average(array, weights=weights)
print("\nWeighted Average:", weighted_average)

# Calculate mean
mean_value = np.mean(array)
print("\nMean:", mean_value)

# Calculate median
median_value = np.median(array)
print("Median:", median_value)

# Calculate standard deviation
std_dev = np.std(array)
print("Standard Deviation:", std_dev)

# Calculate variance
variance_value = np.var(array)
print("Variance:", variance_value)

# Find minimum value
min_value = np.min(array)
print("Minimum value:", min_value)

# Find maximum value
max_value = np.max(array)
print("Maximum value:", max_value)

# Calculate sum
sum_value = np.sum(array)
print("Sum:", sum_value)

# Calculate product
product_value = np.prod(array)
print("Product:", product_value)

Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Weighted Average: 70.0

Mean: 55.0
Median: 55.0
Standard Deviation: 28.722813232690143
Variance: 825.0
Minimum value: 10
Maximum value: 100
Sum: 550
Product: 36288000000000000
